version: "1"
services:
  my-boot-web-app-db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=myDB

  my-boot-web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - my-boot-web-app-db